config:
  job-queue-monitor:CORE_STACK_NAME: Rashad/portfolio-infra/dev
  job-queue-monitor:BUILD_PHASE_TARGET: development
  job-queue-monitor:API_CODE_MOUNT_TARGET: /usr/src/app/api
  job-queue-monitor:SHARED_CODE_MOUNT_TARGET: /usr/src/app/shared
  job-queue-monitor:API_NODE_MODULES_MOUNT_TARGET: /usr/src/app/api/node_modules
  job-queue-monitor:SHARED_NODE_MODULES_MOUNT_TARGET: /usr/src/app/shared/node_modules
  job-queue-monitor:SUB_DOMAIN: jobs
  job-queue-monitor:API_APP_PORT: "3000"
  job-queue-monitor:API_HOST_PORT: "3000"
  job-queue-monitor:UI_APP_PORT: "5173"
  job-queue-monitor:UI_HOST_PORT: "5173"
  job-queue-monitor:DB_NAME:
    secure: AAABABUP7j21PKnR3lVirukzodoGFPQBkxHWk2f9kF0ALbMFB+4Wj69mZUpcxHInMQ==
  job-queue-monitor:DB_USER:
    secure: AAABAHZwMLkowuKS8Q4JXW5nHmsXlxqwuEJZS0v8O0S+4zKwzF4=
  job-queue-monitor:DB_PASSWORD:
    secure: AAABAErauy4o2cuTz6CF5wJ9X2qNqdTm8qSfnDl+ip98DsgWe98=
  job-queue-monitor:DB_PORT:
    secure: AAABANiM6tUx3Bz0eVPWU2dnr/CJz9m2dDHBC4SP2RtcuPSA
  job-queue-monitor:REDIS_PORT: "6379"
